name: templesxtn
favicon: null
layout_spectrum: 0.9974268595688045
typography_spectrum: 0.07215785281732678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5572924998123199
  lightness: 0.22485464764758945
  saturation: 0.9036723577883095
  rhythmicContrast: 0.8477096795104444
purpose: []
